# Generated by Django 4.2.2 on 2024-08-22 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Укажите сумму пожертвования', verbose_name='Сумма пожертвования')),
                ('session_id', models.CharField(blank=True, help_text='Укажите ID сессии', max_length=255, null=True, verbose_name='ID сессии')),
                ('link', models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='ссылка на оплату')),
                ('user', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
