# Generated by Django 4.2.15 on 2024-08-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urok',
            name='kurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uroki', to='materials.kurs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kurs',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите основные материалы и условия курса', null=True, verbose_name='Описание курса'),
        ),
    ]
