# Generated by Django 4.2.15 on 2024-08-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
